# Generated by Django 2.0.6 on 2018-12-02 11:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20181201_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
